init:
  - git config --global core.autocrlf true
build_script:
  - build.cmd --quiet verify
clone_depth: 1
test: off
deploy: off
branches:
  only:
    - master
environment:
  COVERALLS_REPO_TOKEN:
    secure: polBw3WkjnUg+aq0oeBdbqGbszPIgwisEO1SHryVrHTKFxQPd1z8iEmOcTgwtiqZ  
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
matrix:
  fast_finish: true
artifacts:
  - path: 'artifacts\build\*.nupkg'
install:
  - nuget update -self
  - nuget install OpenCover -ExcludeVersion  
  - nuget install coveralls.io -ExcludeVersion  
test_script:
  - OpenCover\tools\OpenCover.Console.exe -register:user -filter:"-[Clif.Tests*]* +[Clif*]*" -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test test\Clif.Tests -appveyor" -output:coverage.xml   
after_test: 
  - coveralls.io\tools\coveralls.net.exe --opencover coverage.xml